name: ROS Industrial CI

on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main
    workflow_dispatch:

jobs:
  industrial_ci:
    strategy:
      matrix:
        ROS_DISTRO: [rolling, jazzy, humble]
        ROS_REPO: [testing, main]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: 'ros-industrial/industrial_ci@master'
        env:
            ROS_DISTRO: ${{ matrix.ROS_DISTRO }}
            ROS_REPO: ${{ matrix.ROS_REPO }}
